<?php
/**
 * Created by PhpStorm.
 * User: vitalie
 * Date: 6/16/15
 * Time: 4:14 PM
 */

namespace REST\Controller;

use Zend\Mvc\Controller\AbstractRestfulController;
use Zend\Stdlib\RequestInterface as Request;
use Zend\Stdlib\ResponseInterface as Response;
use Zend\View\Model\JsonModel;

class UserController extends AbstractRestfulController {

    protected $acceptCriteria = array(
        'Zend\View\Model\JsonModel' => array(
            'application/json',
        ),
    );


    public function get($id)
    {
        $model = $this->acceptableViewModelSelector($this->acceptCriteria);
        $model->id = $id;

        return $model;
    }

    public function create($data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function deleteList($data)
    {
        return parent::deleteList($data); // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }


}