<?php
/**
 * Created by PhpStorm.
 * User: vitalie
 * Date: 6/16/15
 * Time: 4:14 PM
 */

namespace REST\Controller;

use Zend\Mvc\Controller\AbstractRestfulController;
use REST\Service\User;
use Zend\View\Model\JsonModel;


class UserController extends AbstractRestfulController {

    protected $acceptCriteria = array(
        'Zend\View\Model\JsonModel' => array(
            'application/json',
        ),
    );

    /**
     * @var User
     */
    protected $userService;

    public function get($id)
    {
        $model = $this->acceptableViewModelSelector($this->acceptCriteria);
        $model->id = $id;

        return $model;
    }

    public function create($data)
    {


        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function deleteList($data)
    {
        return parent::deleteList($data); // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        $listUsers = $this->getUserService()->getList();

        $model = $this->acceptableViewModelSelector($this->acceptCriteria);
        $model->list = $listUsers;

        return $model;
    }


    /**
     * @return array
     */
    public function getAcceptCriteria()
    {
        return $this->acceptCriteria;
    }

    /**
     * @param array $acceptCriteria
     */
    public function setAcceptCriteria($acceptCriteria)
    {
        $this->acceptCriteria = $acceptCriteria;
    }

    /**
     * @return User
     */
    public function getUserService()
    {
        return $this->userService;
    }

    /**
     * @param User $userService
     */
    public function setUserService($userService)
    {
        $this->userService = $userService;
    }




}